steps:
  - label: "GPU v1.6-nightly"       # change to "v1" when 1.6 is out
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"      # change to "1" when 1.6 is out 
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
